#!/bin/bash
# Script to install various packages on Ubuntu by category

# Update
sudo aptitude update && sudo aptitude full upgrade -y

# Install development essentials
sudo apt-get install linux-headers-$(uname -r) build-essential checkinstall make automake cmake autoconf git git-core --yes

# Install additional development tools
sudo apt-get install module-assistant cmake git checkinstall --yes

# Install compression utilities
sudo aptitude install rar unrar zip unzip unace ntfs-3g nmap vsftpd htop vim bzip2 lzop p7zip-full p7zip-rar openssh-server filezilla -y

# Install more development tools
sudo apt install autoconf automake build-essential dkms fastjar g++ gawk gcc gcc-multilib gettext gettext-base intltool intltool-debian jarwrapper linux-headers-$(uname -r) mawk mesa-common-dev minizip nasm perl perl-base pkg-config subversion wx-common x11proto-record-dev zlib1g zlib1g-dev

# Install libraries and dependencies for development
sudo apt install libalien-wxwidgets-perl libbz2-dev libc6 libcdio-cdda-dev libcdio-dev libcdio-paranoia-dev libcurl3-gnutls libgcc1 libgl1-mesa-dev libglade2-0 libglade2-dev libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libglibmm-2.4-1v5 libglibmm-2.4-dev libglu1-mesa-dev libgmp3-dev libgtk-3-dev libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libgtk2.0-dev libguichan-sdl-0.8.1-1v5 libjack-jackd2-dev liblocale-gettext-perl libpcre16-3 libmodule-pluggable-perl libpng16-16 libsdl-console-dev libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ocaml-dev libsdl-pango-dev libsdl-perl libsdl-sge-dev libsdl-sound1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsdl2-2.0-0 libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev libsigc++-2.0-dev libsndfile1-dev libstdc++6 libtool libvorbisenc2 libwx-perl  libxcb-xtest0 libxcb-xv0 libxml2 libxml2-dev libxml2-utils libxtst-dev libxv-dev libxv1 libxvmc1 libxxf86vm-dev

# Install additional compression utilities
sudo apt install arj bzip2 gzip lhasa liblhasa0 lzip lzma p7zip p7zip-full p7zip-rar sharutils rar unace unrar unrar-free tar unzip xz-utils zip

# Install XFCE desktop environment components
sudo apt install xfce4-appfinder xfce4-appmenu-plugin xfce4-battery-plugin xfce4-clipman xfce4-clipman-plugin xfce4-cpufreq-plugin xfce4-cpugraph-plugin xfce4-datetime-plugin xfce4-dict xfce4-diskperf-plugin xfce4-docklike-plugin  xfce4-eyes-plugin xfce4-fsguard-plugin xfce4-genmon-plugin xfce4-panel xfce4-helpers xfce4-indicator-plugin xfce4-mailwatch-plugin xfce4-mount-plugin xfce4-mpc-plugin xfce4-multiload-ng-plugin xfce4-netload-plugin xfce4-notes xfce4-notes-plugin xfce4-notifyd xfce4-places-plugin xfce4-power-manager xfce4-power-manager-data xfce4-power-manager-plugins xfce4-pulseaudio-plugin xfce4-screenshooter xfce4-sensors-plugin xfce4-session xfce4-settings xfce4-smartbookmark-plugin xfce4-sntray-plugin xfce4-sntray-plugin-common  xfce4-systemload-plugin xfce4-taskmanager xfce4-terminal xfce4-timer-plugin xfce4-verve-plugin xfce4-wavelan-plugin xfce4-weather-plugin xfce4-whiskermenu-plugin  xfce4-xkb-plugin

# Install multimedia related packages
sudo apt install xserver-xorg-video-all libva-drm2 libva-glx2 libva-wayland2 libva-x11-2 libva2 appmenu-gtk2-module appmenu-gtk3-module ayatana-indicator-application libdbusmenu-gtk4

# Install audio-related packages
sudo apt install alsa-firmware-loaders alsa-oss alsa-tools alsa-utils alsamixergui volumeicon-alsa paprefs pavumeter pulseaudio-utils  sound-icons lame libdvdnav4 libdvdread8 libfaac0 libmad0 libmp3lame0 libquicktime2 libstdc++5 libxvidcore4 twolame vorbis-tools x264 gstreamer1.0-alsa gstreamer1.0-adapter-pulseeffects gstreamer1.0-autogain-pulseeffects gstreamer1.0-convolver-pulseeffects gstreamer1.0-crystalizer-pulseeffects gstreamer1.0-espeak gstreamer1.0-fdkaac gstreamer1.0-gl gstreamer1.0-nice gstreamer1.0-pipewire gstreamer1.0-x gstreamer1.0-plugins-bad gstreamer1.0-plugins-bad-apps gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-rtp gstreamer1.0-plugins-ugly gstreamer1.0-pocketsphinx gstreamer1.0-pulseaudio gstreamer1.0-tools gstreamer1.0-vaapi gstreamer1.0-wpe
